name: CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies + coverage tools
        run: |
          pip install --upgrade pip
          pip install -r script_a/requirements.txt
          pip install pytest pytest-cov codecov

      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings --cov=script_a --cov-report=xml -q

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Streamlit Cloud
        uses: streamlit/action@v1
        with:
          email: ${{ secrets.STREAMLIT_EMAIL }}
          password: ${{ secrets.STREAMLIT_PASSWORD }}
